package com.github.matyassladek.ac_wgp.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.eclipse.jdt.annotation.NonNullByDefault;

import java.util.List;

@Getter
@AllArgsConstructor
@NonNullByDefault
public enum Calendar {
    TEST(List.of(
            Track.SPA_FRANCORCHAMPS
    )),
    AC_SEASON_SHORT(List.of(
            Track.IMOLA,
            Track.NURBURGRING,
            Track.SILVERSTONE,
            Track.MONZA,
            Track.SPA_FRANCORCHAMPS
    )),
    AC_SEASON(List.of(
            Track.IMOLA,
            Track.SILVERSTONE,
            Track.SPA_FRANCORCHAMPS,
            Track.ZANDVOORT,
            Track.MONZA,
            Track.NURBURGRING,
            Track.MUGELLO
    )),
    DEFAULT_SEASON(List.of(
            Track.MELBOURNE,
            Track.SEPANG,
            Track.SAKHIR,
            Track.KYALAMI,
            Track.MUGELLO,
            Track.SILVERSTONE,
            Track.SPA_FRANCORCHAMPS,
            Track.BRNO,
            Track.SOKOL,
            Track.BUDDH,
            Track.SUZUKA,
            Track.MONT_TREMBLANT,
            Track.INTERLAGOS
    )),
    SEASON_1(List.of(
            Track.MELBOURNE,
            Track.KYALAMI,
            Track.INTERLAGOS,
            Track.SILVERSTONE,
            Track.BRNO,
            Track.SPIELBERG,
            Track.MUGELLO,
            Track.ROAD_AMERICA,
            Track.SUZUKA
    )),
    SEASON_2(List.of(
            Track.MELBOURNE,
            Track.SEPANG,
            Track.KYALAMI,
            Track.ALGARVE,
            Track.NURBURGRING,
            Track.BRNO,
            Track.SPA_FRANCORCHAMPS,
            Track.MUGELLO,
            Track.SUZUKA,
            Track.ROAD_AMERICA,
            Track.INTERLAGOS
    )),
    SEASON_3(List.of(
            Track.MELBOURNE,
            Track.SEPANG,
            Track.SAKHIR,
            Track.KYALAMI,
            Track.ALGARVE,
            Track.SPIELBERG,
            Track.NURBURGRING,
            Track.BRNO,
            Track.SPA_FRANCORCHAMPS,
            Track.MONZA,
            Track.MONTREAL,
            Track.ROAD_AMERICA,
            Track.CHANG,
            Track.SUZUKA,
            Track.INTERLAGOS
    )),
    SEASON_4(List.of(
            Track.MELBOURNE,
            Track.SEPANG,
            Track.SAKHIR,
            Track.KYALAMI,
            Track.BARCELONA,
            Track.SPIELBERG,
            Track.NURBURGRING,
            Track.MONTREAL,
            Track.WATKINS_GLEN,
            Track.SPA_FRANCORCHAMPS,
            Track.MONZA,
            Track.ALGARVE,
            Track.CHANG,
            Track.ROAD_AMERICA,
            Track.SUZUKA,
            Track.INTERLAGOS
    )),
    SEASON_5(List.of(
            Track.MELBOURNE,
            Track.SEPANG,
            Track.SAKHIR,
            Track.KYALAMI,
            Track.BARCELONA,
            Track.SPIELBERG,
            Track.NURBURGRING,
            Track.MONTREAL,
            Track.WATKINS_GLEN,
            Track.BRNO,
            Track.SPA_FRANCORCHAMPS,
            Track.MONZA,
            Track.MONZA,
            Track.CHANG,
            Track.ROAD_AMERICA,
            Track.SUZUKA,
            Track.INTERLAGOS
    )),
    SEASON_6(List.of(
            Track.MELBOURNE,
            Track.SEPANG,
            Track.SAKHIR,
            Track.KYALAMI,
            Track.BARCELONA,
            Track.SPIELBERG,
            Track.NURBURGRING,
            Track.MONTREAL,
            Track.WATKINS_GLEN,
            Track.SPA_FRANCORCHAMPS,
            Track.MONZA,
            Track.MUGELLO,
            Track.CHANG,
            Track.ROAD_AMERICA,
            Track.SUZUKA,
            Track.INTERLAGOS
    )),
    SEASON_7(List.of(
            Track.MELBOURNE,
            Track.SEPANG,
            Track.SAKHIR,
            Track.KYALAMI,
            Track.BARCELONA,
            Track.NURBURGRING,
            Track.BRNO,
            Track.MONTREAL,
            Track.WATKINS_GLEN,
            Track.SPA_FRANCORCHAMPS,
            Track.MONZA,
            Track.ALGARVE,
            Track.MUGELLO,
            Track.CHANG,
            Track.SUZUKA,
            Track.INTERLAGOS
    )),
    SEASON_8(List.of(
            Track.MELBOURNE,
            Track.SEPANG,
            Track.SAKHIR,
            Track.KYALAMI,
            Track.BARCELONA,
            Track.NURBURGRING,
            Track.BRNO,
            Track.SPIELBERG,
            Track.WATKINS_GLEN,
            Track.SPA_FRANCORCHAMPS,
            Track.MONZA,
            Track.ALGARVE,
            Track.MUGELLO,
            Track.CHANG,
            Track.SUZUKA,
            Track.INTERLAGOS
    ));

    private final List<Track> tracks;
}
