package com.github.matyassladek.ac_wgp.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.eclipse.jdt.annotation.NonNullByDefault;

import java.util.List;

@Getter
@AllArgsConstructor
@NonNullByDefault
public enum Calendar {
    TEST(List.of(
            TrackEnum.SPA_FRANCORCHAMPS
    )),
    AC_SEASON_SHORT(List.of(
            TrackEnum.IMOLA,
            TrackEnum.NURBURGRING,
            TrackEnum.SILVERSTONE,
            TrackEnum.MONZA,
            TrackEnum.SPA_FRANCORCHAMPS
    )),
    AC_SEASON(List.of(
            TrackEnum.IMOLA,
            TrackEnum.SILVERSTONE,
            TrackEnum.SPA_FRANCORCHAMPS,
            TrackEnum.ZANDVOORT,
            TrackEnum.MONZA,
            TrackEnum.NURBURGRING,
            TrackEnum.MUGELLO
    )),
    DEFAULT_SEASON(List.of(
            TrackEnum.MELBOURNE,
            TrackEnum.SEPANG,
            TrackEnum.SAKHIR,
            TrackEnum.KYALAMI,
            TrackEnum.MUGELLO,
            TrackEnum.SILVERSTONE,
            TrackEnum.SPA_FRANCORCHAMPS,
            TrackEnum.BRNO,
            TrackEnum.SOKOL,
            TrackEnum.BUDDH,
            TrackEnum.SUZUKA,
            TrackEnum.MONT_TREMBLANT,
            TrackEnum.INTERLAGOS
    )),
    SEASON_1(List.of(
            TrackEnum.MELBOURNE,
            TrackEnum.KYALAMI,
            TrackEnum.INTERLAGOS,
            TrackEnum.SILVERSTONE,
            TrackEnum.BRNO,
            TrackEnum.SPIELBERG,
            TrackEnum.MUGELLO,
            TrackEnum.ROAD_AMERICA,
            TrackEnum.SUZUKA
    )),
    SEASON_2(List.of(
            TrackEnum.MELBOURNE,
            TrackEnum.SEPANG,
            TrackEnum.KYALAMI,
            TrackEnum.ALGARVE,
            TrackEnum.NURBURGRING,
            TrackEnum.BRNO,
            TrackEnum.SPA_FRANCORCHAMPS,
            TrackEnum.MUGELLO,
            TrackEnum.SUZUKA,
            TrackEnum.ROAD_AMERICA,
            TrackEnum.INTERLAGOS
    )),
    SEASON_3(List.of(
            TrackEnum.MELBOURNE,
            TrackEnum.SEPANG,
            TrackEnum.SAKHIR,
            TrackEnum.KYALAMI,
            TrackEnum.ALGARVE,
            TrackEnum.SPIELBERG,
            TrackEnum.NURBURGRING,
            TrackEnum.BRNO,
            TrackEnum.SPA_FRANCORCHAMPS,
            TrackEnum.MONZA,
            TrackEnum.MONTREAL,
            TrackEnum.ROAD_AMERICA,
            TrackEnum.CHANG,
            TrackEnum.SUZUKA,
            TrackEnum.INTERLAGOS
    )),
    SEASON_4(List.of(
            TrackEnum.MELBOURNE,
            TrackEnum.SEPANG,
            TrackEnum.SAKHIR,
            TrackEnum.KYALAMI,
            TrackEnum.BARCELONA,
            TrackEnum.SPIELBERG,
            TrackEnum.NURBURGRING,
            TrackEnum.MONTREAL,
            TrackEnum.WATKINS_GLEN,
            TrackEnum.SPA_FRANCORCHAMPS,
            TrackEnum.MONZA,
            TrackEnum.ALGARVE,
            TrackEnum.CHANG,
            TrackEnum.ROAD_AMERICA,
            TrackEnum.SUZUKA,
            TrackEnum.INTERLAGOS
    )),
    SEASON_5(List.of(
            TrackEnum.MELBOURNE,
            TrackEnum.SEPANG,
            TrackEnum.SAKHIR,
            TrackEnum.KYALAMI,
            TrackEnum.BARCELONA,
            TrackEnum.SPIELBERG,
            TrackEnum.NURBURGRING,
            TrackEnum.MONTREAL,
            TrackEnum.WATKINS_GLEN,
            TrackEnum.BRNO,
            TrackEnum.SPA_FRANCORCHAMPS,
            TrackEnum.MONZA,
            TrackEnum.MONZA,
            TrackEnum.CHANG,
            TrackEnum.ROAD_AMERICA,
            TrackEnum.SUZUKA,
            TrackEnum.INTERLAGOS
    )),
    SEASON_6(List.of(
            TrackEnum.MELBOURNE,
            TrackEnum.SEPANG,
            TrackEnum.SAKHIR,
            TrackEnum.KYALAMI,
            TrackEnum.BARCELONA,
            TrackEnum.SPIELBERG,
            TrackEnum.NURBURGRING,
            TrackEnum.MONTREAL,
            TrackEnum.WATKINS_GLEN,
            TrackEnum.SPA_FRANCORCHAMPS,
            TrackEnum.MONZA,
            TrackEnum.MUGELLO,
            TrackEnum.CHANG,
            TrackEnum.ROAD_AMERICA,
            TrackEnum.SUZUKA,
            TrackEnum.INTERLAGOS
    )),
    SEASON_7(List.of(
            TrackEnum.MELBOURNE,
            TrackEnum.SEPANG,
            TrackEnum.SAKHIR,
            TrackEnum.KYALAMI,
            TrackEnum.BARCELONA,
            TrackEnum.NURBURGRING,
            TrackEnum.BRNO,
            TrackEnum.MONTREAL,
            TrackEnum.WATKINS_GLEN,
            TrackEnum.SPA_FRANCORCHAMPS,
            TrackEnum.MONZA,
            TrackEnum.ALGARVE,
            TrackEnum.MUGELLO,
            TrackEnum.CHANG,
            TrackEnum.SUZUKA,
            TrackEnum.INTERLAGOS
    )),
    SEASON_8(List.of(
            TrackEnum.MELBOURNE,
            TrackEnum.SEPANG,
            TrackEnum.SAKHIR,
            TrackEnum.KYALAMI,
            TrackEnum.BARCELONA,
            TrackEnum.NURBURGRING,
            TrackEnum.BRNO,
            TrackEnum.SPIELBERG,
            TrackEnum.WATKINS_GLEN,
            TrackEnum.SPA_FRANCORCHAMPS,
            TrackEnum.MONZA,
            TrackEnum.ALGARVE,
            TrackEnum.MUGELLO,
            TrackEnum.CHANG,
            TrackEnum.SUZUKA,
            TrackEnum.INTERLAGOS
    ));

    private final List<TrackEnum> trackEnums;
}
