package com.github.matyassladek.ac_wgp.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.eclipse.jdt.annotation.NonNullByDefault;

/**
 * Flags downloaded from https://flagicons.lipis.dev/
 */
@AllArgsConstructor
@NonNullByDefault
@Getter
public enum Country {

    AND("Andorra", "AND", "/country/ad.svg"),
    ARE("United Arab Emirates", "ARE", "/country/ae.svg"),
    AFG("Afghanistan", "AFG", "/country/af.svg"),
    ATG("Antigua and Barbuda", "ATG", "/country/ag.svg"),
    AIA("Anguilla", "AIA", "/country/ai.svg"),
    ALB("Albania", "ALB", "/country/al.svg"),
    ARM("Armenia", "ARM", "/country/am.svg"),
    AGO("Angola", "AGO", "/country/ao.svg"),
    ATA("Antarctica", "ATA", "/country/aq.svg"),
    ARG("Argentina", "ARG", "/country/ar.svg"),
    ASM("American Samoa", "ASM", "/country/as.svg"),
    AUT("Austria", "AUT", "/country/at.svg"),
    AUS("Australia", "AUS", "/country/au.svg"),
    ABW("Aruba", "ABW", "/country/aw.svg"),
    ALA("Åland Islands", "ALA", "/country/ax.svg"),
    AZE("Azerbaijan", "AZE", "/country/az.svg"),
    BIH("Bosnia and Herzegovina", "BIH", "/country/ba.svg"),
    BRB("Barbados", "BRB", "/country/bb.svg"),
    BGD("Bangladesh", "BGD", "/country/bd.svg"),
    BEL("Belgium", "BEL", "/country/be.svg"),
    BFA("Burkina Faso", "BFA", "/country/bf.svg"),
    BGR("Bulgaria", "BGR", "/country/bg.svg"),
    BHR("Bahrain", "BHR", "/country/bh.svg"),
    BDI("Burundi", "BDI", "/country/bi.svg"),
    BEN("Benin", "BEN", "/country/bj.svg"),
    BLM("Saint Barthélemy", "BLM", "/country/bl.svg"),
    BMU("Bermuda", "BMU", "/country/bm.svg"),
    BRN("Brunei Darussalam", "BRN", "/country/bn.svg"),
    BOL("Bolivia", "BOL", "/country/bo.svg"),
    BES("Bonaire, Sint Eustatius and Saba", "BES", "/country/bq.svg"),
    BRA("Brazil", "BRA", "/country/br.svg"),
    BHS("Bahamas", "BHS", "/country/bs.svg"),
    BTN("Bhutan", "BTN", "/country/bt.svg"),
    BVT("Bouvet Island", "BVT", "/country/bv.svg"),
    BWA("Botswana", "BWA", "/country/bw.svg"),
    BLR("Belarus", "BLR", "/country/by.svg"),
    BLZ("Belize", "BLZ", "/country/bz.svg"),
    CAN("Canada", "CAN", "/country/ca.svg"),
    CCK("Cocos (Keeling) Islands", "CCK", "/country/cc.svg"),
    COD("Congo, Democratic Republic of the", "COD", "/country/cd.svg"),
    CAF("Central African Republic", "CAF", "/country/cf.svg"),
    COG("Congo", "COG", "/country/cg.svg"),
    CHE("Switzerland", "CHE", "/country/ch.svg"),
    CIV("Côte d'Ivoire", "CIV", "/country/ci.svg"),
    COK("Cook Islands", "COK", "/country/ck.svg"),
    CHL("Chile", "CHL", "/country/cl.svg"),
    CMR("Cameroon", "CMR", "/country/cm.svg"),
    CHN("China", "CHN", "/country/cn.svg"),
    COL("Colombia", "COL", "/country/co.svg"),
    CRI("Costa Rica", "CRI", "/country/cr.svg"),
    CUB("Cuba", "CUB", "/country/cu.svg"),
    CPV("Cabo Verde", "CPV", "/country/cv.svg"),
    CUW("Curaçao", "CUW", "/country/cw.svg"),
    CXR("Christmas Island", "CXR", "/country/cx.svg"),
    CYP("Cyprus", "CYP", "/country/cy.svg"),
    CZE("Czechia", "CZE", "/country/cz.svg"),
    DEU("Germany", "DEU", "/country/de.svg"),
    DJI("Djibouti", "DJI", "/country/dj.svg"),
    DNK("Denmark", "DNK", "/country/dk.svg"),
    DMA("Dominica", "DMA", "/country/dm.svg"),
    DOM("Dominican Republic", "DOM", "/country/do.svg"),
    DZA("Algeria", "DZA", "/country/dz.svg"),
    ECU("Ecuador", "ECU", "/country/ec.svg"),
    EST("Estonia", "EST", "/country/ee.svg"),
    EGY("Egypt", "EGY", "/country/eg.svg"),
    ESH("Western Sahara", "ESH", "/country/eh.svg"),
    ERI("Eritrea", "ERI", "/country/er.svg"),
    ESP("Spain", "ESP", "/country/es.svg"),
    ETH("Ethiopia", "ETH", "/country/et.svg"),
    FIN("Finland", "FIN", "/country/fi.svg"),
    FJI("Fiji", "FJI", "/country/fj.svg"),
    FLK("Falkland Islands (Malvinas)", "FLK", "/country/fk.svg"),
    FSM("Micronesia (Federated States of)", "FSM", "/country/fm.svg"),
    FRO("Faroe Islands", "FRO", "/country/fo.svg"),
    FRA("France", "FRA", "/country/fr.svg"),
    GAB("Gabon", "GAB", "/country/ga.svg"),
    GBR("United Kingdom", "GBR", "/country/gb.svg"),
    GRD("Grenada", "GRD", "/country/gd.svg"),
    GEO("Georgia", "GEO", "/country/ge.svg"),
    GUF("French Guiana", "GUF", "/country/gf.svg"),
    GGY("Guernsey", "GGY", "/country/gg.svg"),
    GHA("Ghana", "GHA", "/country/gh.svg"),
    GIB("Gibraltar", "GIB", "/country/gi.svg"),
    GRL("Greenland", "GRL", "/country/gl.svg"),
    GMB("Gambia", "GMB", "/country/gm.svg"),
    GIN("Guinea", "GIN", "/country/gn.svg"),
    GLP("Guadeloupe", "GLP", "/country/gp.svg"),
    GNQ("Equatorial Guinea", "GNQ", "/country/gq.svg"),
    GRC("Greece", "GRC", "/country/gr.svg"),
    GTM("Guatemala", "GTM", "/country/gt.svg"),
    GUM("Guam", "GUM", "/country/gu.svg"),
    GNB("Guinea-Bissau", "GNB", "/country/gw.svg"),
    GUY("Guyana", "GUY", "/country/gy.svg"),
    HKG("Hong Kong", "HKG", "/country/hk.svg"),
    HMD("Heard Island and McDonald Islands", "HMD", "/country/hm.svg"),
    HND("Honduras", "HND", "/country/hn.svg"),
    HRV("Croatia", "HRV", "/country/hr.svg"),
    HTI("Haiti", "HTI", "/country/ht.svg"),
    HUN("Hungary", "HUN", "/country/hu.svg"),
    IDN("Indonesia", "IDN", "/country/id.svg"),
    IRL("Ireland", "IRL", "/country/ie.svg"),
    ISR("Israel", "ISR", "/country/il.svg"),
    IMN("Isle of Man", "IMN", "/country/im.svg"),
    IND("India", "IND", "/country/in.svg"),
    IOT("British Indian Ocean Territory", "IOT", "/country/io.svg"),
    IRQ("Iraq", "IRQ", "/country/iq.svg"),
    IRN("Iran", "IRN", "/country/ir.svg"),
    ISL("Iceland", "ISL", "/country/is.svg"),
    ITA("Italy", "ITA", "/country/it.svg"),
    JEY("Jersey", "JEY", "/country/je.svg"),
    JAM("Jamaica", "JAM", "/country/jm.svg"),
    JOR("Jordan", "JOR", "/country/jo.svg"),
    JPN("Japan", "JPN", "/country/jp.svg"),
    KEN("Kenya", "KEN", "/country/ke.svg"),
    KGZ("Kyrgyzstan", "KGZ", "/country/kg.svg"),
    KHM("Cambodia", "KHM", "/country/kh.svg"),
    KIR("Kiribati", "KIR", "/country/ki.svg"),
    COM("Comoros", "COM", "/country/km.svg"),
    KNA("Saint Kitts and Nevis", "KNA", "/country/kn.svg"),
    PRK("Korea (North)", "PRK", "/country/kp.svg"),
    KOR("Korea (South)", "KOR", "/country/kr.svg"),
    KWT("Kuwait", "KWT", "/country/kw.svg"),
    CYM("Cayman Islands", "CYM", "/country/ky.svg"),
    KAZ("Kazakhstan", "KAZ", "/country/kz.svg"),
    LAO("Lao People's Democratic Republic", "LAO", "/country/la.svg"),
    LBN("Lebanon", "LBN", "/country/lb.svg"),
    LCA("Saint Lucia", "LCA", "/country/lc.svg"),
    LIE("Liechtenstein", "LIE", "/country/li.svg"),
    LKA("Sri Lanka", "LKA", "/country/lk.svg"),
    LBR("Liberia", "LBR", "/country/lr.svg"),
    LSO("Lesotho", "LSO", "/country/ls.svg"),
    LTU("Lithuania", "LTU", "/country/lt.svg"),
    LUX("Luxembourg", "LUX", "/country/lu.svg"),
    LVA("Latvia", "LVA", "/country/lv.svg"),
    LBY("Libya", "LBY", "/country/ly.svg"),
    MAR("Morocco", "MAR", "/country/ma.svg"),
    MCO("Monaco", "MCO", "/country/mc.svg"),
    MDA("Moldova", "MDA", "/country/md.svg"),
    MNE("Montenegro", "MNE", "/country/me.svg"),
    MDG("Madagascar", "MDG", "/country/mg.svg"),
    MHL("Marshall Islands", "MHL", "/country/mh.svg"),
    MKD("North Macedonia", "MKD", "/country/mk.svg"),
    MLI("Mali", "MLI", "/country/ml.svg"),
    MMR("Myanmar", "MMR", "/country/mm.svg"),
    MNG("Mongolia", "MNG", "/country/mn.svg"),
    MNP("Northern Mariana Islands", "MNP", "/country/mp.svg"),
    MOZ("Mozambique", "MOZ", "/country/mz.svg"),
    MEX("Mexico", "MEX", "/country/mx.svg"),
    MYS("Malaysia", "MYS", "/country/my.svg"),
    MYT("Mayotte", "MYT", "/country/yt.svg"),
    NAM("Namibia", "NAM", "/country/na.svg"),
    NCL("New Caledonia", "NCL", "/country/nc.svg"),
    NER("Niger", "NER", "/country/ne.svg"),
    NFK("Norfolk Island", "NFK", "/country/nf.svg"),
    NGA("Nigeria", "NGA", "/country/ng.svg"),
    NIC("Nicaragua", "NIC", "/country/ni.svg"),
    NLD("Netherlands", "NLD", "/country/nl.svg"),
    NOR("Norway", "NOR", "/country/no.svg"),
    NPL("Nepal", "NPL", "/country/np.svg"),
    NRU("Nauru", "NRU", "/country/nr.svg"),
    NZL("New Zealand", "NZL", "/country/nz.svg"),
    OMN("Oman", "OMN", "/country/om.svg"),
    PAN("Panama", "PAN", "/country/pa.svg"),
    PER("Peru", "PER", "/country/pe.svg"),
    PYF("French Polynesia", "PYF", "/country/pf.svg"),
    svg("Papua New Guinea", "svg", "/country/pg.svg"),
    PHL("Philippines", "PHL", "/country/ph.svg"),
    PAK("Pakistan", "PAK", "/country/pk.svg"),
    POL("Poland", "POL", "/country/pl.svg"),
    SPM("Saint Pierre and Miquelon", "SPM", "/country/pm.svg"),
    PCN("Pitcairn", "PCN", "/country/pn.svg"),
    PRT("Portugal", "PRT", "/country/pt.svg"),
    PLW("Palau", "PLW", "/country/pw.svg"),
    PRY("Paraguay", "PRY", "/country/py.svg"),
    QAT("Qatar", "QAT", "/country/qa.svg"),
    REU("Réunion", "REU", "/country/re.svg"),
    ROU("Romania", "ROU", "/country/ro.svg"),
    SRB("Serbia", "SRB", "/country/rs.svg"),
    RUS("Russian Federation", "RUS", "/country/ru.svg"),
    RWA("Rwanda", "RWA", "/country/rw.svg"),
    SAU("Saudi Arabia", "SAU", "/country/sa.svg"),
    SLB("Solomon Islands", "SLB", "/country/sb.svg"),
    SYC("Seychelles", "SYC", "/country/sc.svg"),
    SDN("Sudan", "SDN", "/country/sd.svg"),
    SWE("Sweden", "SWE", "/country/se.svg"),
    SGP("Singapore", "SGP", "/country/sg.svg"),
    SHN("Saint Helena, Ascension and Tristan da Cunha", "SHN", "/country/sh.svg"),
    SVN("Slovenia", "SVN", "/country/si.svg"),
    SJM("Svalbard and Jan Mayen", "SJM", "/country/sj.svg"),
    SVK("Slovakia", "SVK", "/country/sk.svg"),
    SLE("Sierra Leone", "SLE", "/country/sl.svg"),
    SMR("San Marino", "SMR", "/country/sm.svg"),
    SEN("Senegal", "SEN", "/country/sn.svg"),
    SOM("Somalia", "SOM", "/country/so.svg"),
    SUR("Suriname", "SUR", "/country/sr.svg"),
    SSD("South Sudan", "SSD", "/country/ss.svg"),
    STP("Sao Tome and Principe", "STP", "/country/st.svg"),
    SLV("El Salvador", "SLV", "/country/sv.svg"),
    SXM("Sint Maarten", "SXM", "/country/sx.svg"),
    SYR("Syrian Arab Republic", "SYR", "/country/sy.svg"),
    SWZ("Eswatini", "SWZ", "/country/sz.svg"),
    TCA("Turks and Caicos Islands", "TCA", "/country/tc.svg"),
    TCD("Chad", "TCD", "/country/td.svg"),
    ATF("French Southern Territories", "ATF", "/country/tf.svg"),
    TGO("Togo", "TGO", "/country/tg.svg"),
    THA("Thailand", "THA", "/country/th.svg"),
    TJK("Tajikistan", "TJK", "/country/tj.svg"),
    TKL("Tokelau", "TKL", "/country/tk.svg"),
    TLS("Timor-Leste", "TLS", "/country/tl.svg"),
    TKM("Turkmenistan", "TKM", "/country/tm.svg"),
    TUN("Tunisia", "TUN", "/country/tn.svg"),
    TON("Tonga", "TON", "/country/to.svg"),
    TUR("Turkey", "TUR", "/country/tr.svg"),
    TTO("Trinidad and Tobago", "TTO", "/country/tt.svg"),
    TUV("Tuvalu", "TUV", "/country/tv.svg"),
    TWN("Taiwan", "TWN", "/country/tw.svg"),
    TZA("Tanzania", "TZA", "/country/tz.svg"),
    UKR("Ukraine", "UKR", "/country/ua.svg"),
    UGA("Uganda", "UGA", "/country/ug.svg"),
    UMI("United States Minor Outlying Islands", "UMI", "/country/um.svg"),
    USA("United States", "USA", "/country/us.svg"),
    URY("Uruguay", "URY", "/country/uy.svg"),
    UZB("Uzbekistan", "UZB", "/country/uz.svg"),
    VAT("Holy See (Vatican City State)", "VAT", "/country/va.svg"),
    VCT("Saint Vincent and the Grenadines", "VCT", "/country/vc.svg"),
    VEN("Venezuela", "VEN", "/country/ve.svg"),
    VGB("Virgin Islands (British)", "VGB", "/country/vg.svg"),
    VIR("Virgin Islands (U.S.)", "VIR", "/country/vi.svg"),
    VNM("Viet Nam", "VNM", "/country/vn.svg"),
    VUT("Vanuatu", "VUT", "/country/vu.svg"),
    WLF("Wallis and Futuna", "WLF", "/country/wf.svg"),
    WSM("Samoa", "WSM", "/country/ws.svg"),
    YEM("Yemen", "YEM", "/country/ye.svg"),
    YT("Mayotte", "MYT", "/country/yt.svg"),    // Variable 'MYT' is already defined in the scope
    ZAF("South Africa", "ZAF", "/country/za.svg"),
    ZMB("Zambia", "ZMB", "/country/zm.svg"),
    ZWE("Zimbabwe", "ZWE", "/country/zw.svg");

    private final String name;
    private final String code;
    private final String flag;
}
