package com.github.matyassladek.ac_wgp.model;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.eclipse.jdt.annotation.NonNullByDefault;

/**
 * Flags downloaded from https://flagpedia.net/download/images
 */
@AllArgsConstructor
@NonNullByDefault
@Getter
public enum Country {

    AND("Andorra", "AND", "/country/ad.png"),
    ARE("United Arab Emirates", "ARE", "/country/ae.png"),
    AFG("Afghanistan", "AFG", "/country/af.png"),
    ATG("Antigua and Barbuda", "ATG", "/country/ag.png"),
    AIA("Anguilla", "AIA", "/country/ai.png"),
    ALB("Albania", "ALB", "/country/al.png"),
    ARM("Armenia", "ARM", "/country/am.png"),
    AGO("Angola", "AGO", "/country/ao.png"),
    ATA("Antarctica", "ATA", "/country/aq.png"),
    ARG("Argentina", "ARG", "/country/ar.png"),
    ASM("American Samoa", "ASM", "/country/as.png"),
    AUT("Austria", "AUT", "/country/at.png"),
    AUS("Australia", "AUS", "/country/au.png"),
    ABW("Aruba", "ABW", "/country/aw.png"),
    ALA("Åland Islands", "ALA", "/country/ax.png"),
    AZE("Azerbaijan", "AZE", "/country/az.png"),
    BIH("Bosnia and Herzegovina", "BIH", "/country/ba.png"),
    BRB("Barbados", "BRB", "/country/bb.png"),
    BGD("Bangladesh", "BGD", "/country/bd.png"),
    BEL("Belgium", "BEL", "/country/be.png"),
    BFA("Burkina Faso", "BFA", "/country/bf.png"),
    BGR("Bulgaria", "BGR", "/country/bg.png"),
    BHR("Bahrain", "BHR", "/country/bh.png"),
    BDI("Burundi", "BDI", "/country/bi.png"),
    BEN("Benin", "BEN", "/country/bj.png"),
    BLM("Saint Barthélemy", "BLM", "/country/bl.png"),
    BMU("Bermuda", "BMU", "/country/bm.png"),
    BRN("Brunei Darussalam", "BRN", "/country/bn.png"),
    BOL("Bolivia", "BOL", "/country/bo.png"),
    BES("Bonaire, Sint Eustatius and Saba", "BES", "/country/bq.png"),
    BRA("Brazil", "BRA", "/country/br.png"),
    BHS("Bahamas", "BHS", "/country/bs.png"),
    BTN("Bhutan", "BTN", "/country/bt.png"),
    BVT("Bouvet Island", "BVT", "/country/bv.png"),
    BWA("Botswana", "BWA", "/country/bw.png"),
    BLR("Belarus", "BLR", "/country/by.png"),
    BLZ("Belize", "BLZ", "/country/bz.png"),
    CAN("Canada", "CAN", "/country/ca.png"),
    CCK("Cocos (Keeling) Islands", "CCK", "/country/cc.png"),
    COD("Congo, Democratic Republic of the", "COD", "/country/cd.png"),
    CAF("Central African Republic", "CAF", "/country/cf.png"),
    COG("Congo", "COG", "/country/cg.png"),
    CHE("Switzerland", "CHE", "/country/ch.png"),
    CIV("Côte d'Ivoire", "CIV", "/country/ci.png"),
    COK("Cook Islands", "COK", "/country/ck.png"),
    CHL("Chile", "CHL", "/country/cl.png"),
    CMR("Cameroon", "CMR", "/country/cm.png"),
    CHN("China", "CHN", "/country/cn.png"),
    COL("Colombia", "COL", "/country/co.png"),
    CRI("Costa Rica", "CRI", "/country/cr.png"),
    CUB("Cuba", "CUB", "/country/cu.png"),
    CPV("Cabo Verde", "CPV", "/country/cv.png"),
    CUW("Curaçao", "CUW", "/country/cw.png"),
    CXR("Christmas Island", "CXR", "/country/cx.png"),
    CYP("Cyprus", "CYP", "/country/cy.png"),
    CZE("Czechia", "CZE", "/country/cz.png"),
    DEU("Germany", "DEU", "/country/de.png"),
    DJI("Djibouti", "DJI", "/country/dj.png"),
    DNK("Denmark", "DNK", "/country/dk.png"),
    DMA("Dominica", "DMA", "/country/dm.png"),
    DOM("Dominican Republic", "DOM", "/country/do.png"),
    DZA("Algeria", "DZA", "/country/dz.png"),
    ECU("Ecuador", "ECU", "/country/ec.png"),
    EST("Estonia", "EST", "/country/ee.png"),
    EGY("Egypt", "EGY", "/country/eg.png"),
    ESH("Western Sahara", "ESH", "/country/eh.png"),
    ERI("Eritrea", "ERI", "/country/er.png"),
    ESP("Spain", "ESP", "/country/es.png"),
    ETH("Ethiopia", "ETH", "/country/et.png"),
    FIN("Finland", "FIN", "/country/fi.png"),
    FJI("Fiji", "FJI", "/country/fj.png"),
    FLK("Falkland Islands (Malvinas)", "FLK", "/country/fk.png"),
    FSM("Micronesia (Federated States of)", "FSM", "/country/fm.png"),
    FRO("Faroe Islands", "FRO", "/country/fo.png"),
    FRA("France", "FRA", "/country/fr.png"),
    GAB("Gabon", "GAB", "/country/ga.png"),
    GBR("United Kingdom", "GBR", "/country/gb.png"),
    GRD("Grenada", "GRD", "/country/gd.png"),
    GEO("Georgia", "GEO", "/country/ge.png"),
    GUF("French Guiana", "GUF", "/country/gf.png"),
    GGY("Guernsey", "GGY", "/country/gg.png"),
    GHA("Ghana", "GHA", "/country/gh.png"),
    GIB("Gibraltar", "GIB", "/country/gi.png"),
    GRL("Greenland", "GRL", "/country/gl.png"),
    GMB("Gambia", "GMB", "/country/gm.png"),
    GIN("Guinea", "GIN", "/country/gn.png"),
    GLP("Guadeloupe", "GLP", "/country/gp.png"),
    GNQ("Equatorial Guinea", "GNQ", "/country/gq.png"),
    GRC("Greece", "GRC", "/country/gr.png"),
    GTM("Guatemala", "GTM", "/country/gt.png"),
    GUM("Guam", "GUM", "/country/gu.png"),
    GNB("Guinea-Bissau", "GNB", "/country/gw.png"),
    GUY("Guyana", "GUY", "/country/gy.png"),
    HKG("Hong Kong", "HKG", "/country/hk.png"),
    HMD("Heard Island and McDonald Islands", "HMD", "/country/hm.png"),
    HND("Honduras", "HND", "/country/hn.png"),
    HRV("Croatia", "HRV", "/country/hr.png"),
    HTI("Haiti", "HTI", "/country/ht.png"),
    HUN("Hungary", "HUN", "/country/hu.png"),
    IDN("Indonesia", "IDN", "/country/id.png"),
    IRL("Ireland", "IRL", "/country/ie.png"),
    ISR("Israel", "ISR", "/country/il.png"),
    IMN("Isle of Man", "IMN", "/country/im.png"),
    IND("India", "IND", "/country/in.png"),
    IOT("British Indian Ocean Territory", "IOT", "/country/io.png"),
    IRQ("Iraq", "IRQ", "/country/iq.png"),
    IRN("Iran", "IRN", "/country/ir.png"),
    ISL("Iceland", "ISL", "/country/is.png"),
    ITA("Italy", "ITA", "/country/it.png"),
    JEY("Jersey", "JEY", "/country/je.png"),
    JAM("Jamaica", "JAM", "/country/jm.png"),
    JOR("Jordan", "JOR", "/country/jo.png"),
    JPN("Japan", "JPN", "/country/jp.png"),
    KEN("Kenya", "KEN", "/country/ke.png"),
    KGZ("Kyrgyzstan", "KGZ", "/country/kg.png"),
    KHM("Cambodia", "KHM", "/country/kh.png"),
    KIR("Kiribati", "KIR", "/country/ki.png"),
    COM("Comoros", "COM", "/country/km.png"),
    KNA("Saint Kitts and Nevis", "KNA", "/country/kn.png"),
    PRK("Korea (North)", "PRK", "/country/kp.png"),
    KOR("Korea (South)", "KOR", "/country/kr.png"),
    KWT("Kuwait", "KWT", "/country/kw.png"),
    CYM("Cayman Islands", "CYM", "/country/ky.png"),
    KAZ("Kazakhstan", "KAZ", "/country/kz.png"),
    LAO("Lao People's Democratic Republic", "LAO", "/country/la.png"),
    LBN("Lebanon", "LBN", "/country/lb.png"),
    LCA("Saint Lucia", "LCA", "/country/lc.png"),
    LIE("Liechtenstein", "LIE", "/country/li.png"),
    LKA("Sri Lanka", "LKA", "/country/lk.png"),
    LBR("Liberia", "LBR", "/country/lr.png"),
    LSO("Lesotho", "LSO", "/country/ls.png"),
    LTU("Lithuania", "LTU", "/country/lt.png"),
    LUX("Luxembourg", "LUX", "/country/lu.png"),
    LVA("Latvia", "LVA", "/country/lv.png"),
    LBY("Libya", "LBY", "/country/ly.png"),
    MAR("Morocco", "MAR", "/country/ma.png"),
    MCO("Monaco", "MCO", "/country/mc.png"),
    MDA("Moldova", "MDA", "/country/md.png"),
    MNE("Montenegro", "MNE", "/country/me.png"),
    MDG("Madagascar", "MDG", "/country/mg.png"),
    MHL("Marshall Islands", "MHL", "/country/mh.png"),
    MKD("North Macedonia", "MKD", "/country/mk.png"),
    MLI("Mali", "MLI", "/country/ml.png"),
    MMR("Myanmar", "MMR", "/country/mm.png"),
    MNG("Mongolia", "MNG", "/country/mn.png"),
    MNP("Northern Mariana Islands", "MNP", "/country/mp.png"),
    MOZ("Mozambique", "MOZ", "/country/mz.png"),
    MEX("Mexico", "MEX", "/country/mx.png"),
    MYS("Malaysia", "MYS", "/country/my.png"),
    MYT("Mayotte", "MYT", "/country/yt.png"),
    NAM("Namibia", "NAM", "/country/na.png"),
    NCL("New Caledonia", "NCL", "/country/nc.png"),
    NER("Niger", "NER", "/country/ne.png"),
    NFK("Norfolk Island", "NFK", "/country/nf.png"),
    NGA("Nigeria", "NGA", "/country/ng.png"),
    NIC("Nicaragua", "NIC", "/country/ni.png"),
    NLD("Netherlands", "NLD", "/country/nl.png"),
    NOR("Norway", "NOR", "/country/no.png"),
    NPL("Nepal", "NPL", "/country/np.png"),
    NRU("Nauru", "NRU", "/country/nr.png"),
    NZL("New Zealand", "NZL", "/country/nz.png"),
    OMN("Oman", "OMN", "/country/om.png"),
    PAN("Panama", "PAN", "/country/pa.png"),
    PER("Peru", "PER", "/country/pe.png"),
    PYF("French Polynesia", "PYF", "/country/pf.png"),
    PNG("Papua New Guinea", "PNG", "/country/pg.png"),
    PHL("Philippines", "PHL", "/country/ph.png"),
    PAK("Pakistan", "PAK", "/country/pk.png"),
    POL("Poland", "POL", "/country/pl.png"),
    SPM("Saint Pierre and Miquelon", "SPM", "/country/pm.png"),
    PCN("Pitcairn", "PCN", "/country/pn.png"),
    PRT("Portugal", "PRT", "/country/pt.png"),
    PLW("Palau", "PLW", "/country/pw.png"),
    PRY("Paraguay", "PRY", "/country/py.png"),
    QAT("Qatar", "QAT", "/country/qa.png"),
    REU("Réunion", "REU", "/country/re.png"),
    ROU("Romania", "ROU", "/country/ro.png"),
    SRB("Serbia", "SRB", "/country/rs.png"),
    RUS("Russian Federation", "RUS", "/country/ru.png"),
    RWA("Rwanda", "RWA", "/country/rw.png"),
    SAU("Saudi Arabia", "SAU", "/country/sa.png"),
    SLB("Solomon Islands", "SLB", "/country/sb.png"),
    SYC("Seychelles", "SYC", "/country/sc.png"),
    SDN("Sudan", "SDN", "/country/sd.png"),
    SWE("Sweden", "SWE", "/country/se.png"),
    SGP("Singapore", "SGP", "/country/sg.png"),
    SHN("Saint Helena, Ascension and Tristan da Cunha", "SHN", "/country/sh.png"),
    SVN("Slovenia", "SVN", "/country/si.png"),
    SJM("Svalbard and Jan Mayen", "SJM", "/country/sj.png"),
    SVK("Slovakia", "SVK", "/country/sk.png"),
    SLE("Sierra Leone", "SLE", "/country/sl.png"),
    SMR("San Marino", "SMR", "/country/sm.png"),
    SEN("Senegal", "SEN", "/country/sn.png"),
    SOM("Somalia", "SOM", "/country/so.png"),
    SUR("Suriname", "SUR", "/country/sr.png"),
    SSD("South Sudan", "SSD", "/country/ss.png"),
    STP("Sao Tome and Principe", "STP", "/country/st.png"),
    SLV("El Salvador", "SLV", "/country/sv.png"),
    SXM("Sint Maarten", "SXM", "/country/sx.png"),
    SYR("Syrian Arab Republic", "SYR", "/country/sy.png"),
    SWZ("Eswatini", "SWZ", "/country/sz.png"),
    TCA("Turks and Caicos Islands", "TCA", "/country/tc.png"),
    TCD("Chad", "TCD", "/country/td.png"),
    ATF("French Southern Territories", "ATF", "/country/tf.png"),
    TGO("Togo", "TGO", "/country/tg.png"),
    THA("Thailand", "THA", "/country/th.png"),
    TJK("Tajikistan", "TJK", "/country/tj.png"),
    TKL("Tokelau", "TKL", "/country/tk.png"),
    TLS("Timor-Leste", "TLS", "/country/tl.png"),
    TKM("Turkmenistan", "TKM", "/country/tm.png"),
    TUN("Tunisia", "TUN", "/country/tn.png"),
    TON("Tonga", "TON", "/country/to.png"),
    TUR("Turkey", "TUR", "/country/tr.png"),
    TTO("Trinidad and Tobago", "TTO", "/country/tt.png"),
    TUV("Tuvalu", "TUV", "/country/tv.png"),
    TWN("Taiwan", "TWN", "/country/tw.png"),
    TZA("Tanzania", "TZA", "/country/tz.png"),
    UKR("Ukraine", "UKR", "/country/ua.png"),
    UGA("Uganda", "UGA", "/country/ug.png"),
    UMI("United States Minor Outlying Islands", "UMI", "/country/um.png"),
    USA("United States", "USA", "/country/us.png"),
    URY("Uruguay", "URY", "/country/uy.png"),
    UZB("Uzbekistan", "UZB", "/country/uz.png"),
    VAT("Holy See (Vatican City State)", "VAT", "/country/va.png"),
    VCT("Saint Vincent and the Grenadines", "VCT", "/country/vc.png"),
    VEN("Venezuela", "VEN", "/country/ve.png"),
    VGB("Virgin Islands (British)", "VGB", "/country/vg.png"),
    VIR("Virgin Islands (U.S.)", "VIR", "/country/vi.png"),
    VNM("Viet Nam", "VNM", "/country/vn.png"),
    VUT("Vanuatu", "VUT", "/country/vu.png"),
    WLF("Wallis and Futuna", "WLF", "/country/wf.png"),
    WSM("Samoa", "WSM", "/country/ws.png"),
    YEM("Yemen", "YEM", "/country/ye.png"),
    YT("Mayotte", "MYT", "/country/yt.png"),    // Variable 'MYT' is already defined in the scope
    ZAF("South Africa", "ZAF", "/country/za.png"),
    ZMB("Zambia", "ZMB", "/country/zm.png"),
    ZWE("Zimbabwe", "ZWE", "/country/zw.png");

    private final String name;
    private final String code;
    private final String flag;
}
